### ISSUE TITLE
not found image links

### ISSUE THREAD

**Issue by 0xdwong** [the-web3/layer2#6]
- File [https://github.com/the-web3/layer2/blob/main/code/arbitrum/setup.md](https://github.com/the-web3/layer2/blob/main/code/arbitrum/setup.md), line:33,87
- File [https://github.com/the-web3/layer2/blob/main/src/optimistim-metis-boba.md](https://github.com/the-web3/layer2/blob/main/src/optimistim-metis-boba.md), line 27

**Comment by guoshijiang** [comment]
done
